version: "3.6"
services:
    bind:
        container_name: bind
        hostname: bind
        network_mode: bridge
        image: drseussfreak/bind
        restart: unless-stopped
        ports:
            - serverip:53:53/tcp
            - serverip:53:53/udp
            - 10000:10000/tcp
        volumes:
            - /path/to/bind/data:/data
        environment:
            - WEBMIN_ENABLED=true
            - WEBMIN_INIT_SSL_ENABLED=false
            - WEBMIN_INIT_REFERERS=dns.domain.com
            - WEBMIN_INIT_REDIRECT_PORT=10000
            - ROOT_PASSWORD=password
            - TZ=America/Chicago
